### ISSUE TITLE
Example usage code with this image format 

### ISSUE THREAD

**Issue by RahulBhalley** [heestand-xyz/PNG3D#1]
Example usage code with this image format which can be viewed in SwiftUI?

**Comment by heestand-xyz** [comment]
This format is mainly built for [AsyncGraphics](http://github.com/heestand-xyz/AsyncGraphics), please see the docs [here](http://async.graphics). You can view the voxel data with a [Graphic3DView](https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/graphic3dview).
